apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
      - main
      - test-branch
  pull_request:
    branches:
      - test-branch-2
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    outputs:
      zxcvbxvz: z`cxvbxz`
  Test Job:
    steps:
      - name: Test Step
        uses: cloudbees-io/checkout
    outputs:
      dtfghfgdfsd: dsfghhkjfhdg
env:
  Value: Value2
